service: testdyno
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  profile: testuser
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "lambda:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource: "arn:aws:execute-api:ap-south-1:019447061794:03t7vnqzy7/*"
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

functions:
  connect:
    handler: src/routes/chat.connectHandler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: src/routes/chat.disconnectHandler
    events:
      - websocket:
          route: $disconnect

  sendMessage:
    handler: src/routes/chat.sendMessageHandler
    events:
      - websocket:
          route: sendMessage

  getMessages:
    handler: src/routes/chat.getMessagesHandler
    events:
      - httpApi:
          path: /messages
          method: get

plugins:
  - serverless-offline

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connections
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: ConnectionId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
          - AttributeName: ConnectionId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages
        AttributeDefinitions:
          - AttributeName: ConversationId
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: ConversationId
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5


package:
  individually: true
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

custom:
  serverless-offline:
    httpPort: 9090
